# Generated by Django 4.1 on 2023-02-25 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created", "-body")},
        ),
    ]
